name: Build
on:
  push:
    branches:
      - master
      - actions

jobs:
  build: 
    name: Minify
    runs-on: ubuntu-latest
    container: thekevjames/minify:2.5.2
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
        with:
          ref: ${{ github.ref }}

      - name: Minify
        run: minify --recursive --output . .

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: src
          path: |
            index.html
            error.html
            pgp.asc.txt
            assets/
            android-chrome-192x192.png
            android-chrome-512x512.png
            apple-touch-icon.png
            favicon-16x16.png
            favicon-32x32.png
            favicon.ico
            favicon.png
            site.webmanifest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: src

# == jbeardllc.com deployment
      - name: jbeardllc.com - Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
            --exclude ".git\*"
            --exclude "README.md"
            --exclude "docker-compose.yml"
        env:
          AWS_S3_BUCKET: ${{ secrets.JBEARDLLC_AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.JBEARDLLC_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.JBEARDLLC_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-2'
          SOURCE_DIR: '.'

      - name: jbeardllc.com - Invalidate CloudFront Cache
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.JBEARDLLC_CF_DISTRIBUTION }}
          PATHS: "/*"
          AWS_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.JBEARDLLC_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.JBEARDLLC_AWS_SECRET_ACCESS_KEY }}

# == jbeard.dev deployment
      - name: jbeard.dev - Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
            --exclude ".git\*"
            --exclude "README.md"
            --exclude "docker-compose.yml"
        env:
          AWS_S3_BUCKET: ${{ secrets.JBEARDDEV_AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.JBEARDDEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.JBEARDDEV_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-2'
          SOURCE_DIR: '.'

      - name: jbeard.dev - Invalidate CloudFront Cache
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.JBEARDDEV_CF_DISTRIBUTION }}
          PATHS: "/*"
          AWS_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.JBEARDDEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.JBEARDDEV_AWS_SECRET_ACCESS_KEY }}

